services:
  - type: web
    name: location
    healthCheckPath: /
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true